# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: MAS Dialogue Generator

# Short description (goes below the title; it will also be used in the RSS feed)
description: A Basic dialogue generator for Monika After Story.

# Your name, as you want it to appear underneath each post and in the footer
author: vermicellibug

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, LICENSE, DISCLAIMER.md]